// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOORPm7AP1SKj6S1GLsvdlKjCrUeJeQkE',
    appId: '1:106435358280:web:3510efc4c45ad79554b27d',
    messagingSenderId: '106435358280',
    projectId: 'pairplay-e91f9',
    authDomain: 'pairplay-e91f9.firebaseapp.com',
    storageBucket: 'pairplay-e91f9.firebasestorage.app',
    measurementId: 'G-M6YKLJSJST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADkhd7Hyig-P62cUTQlj1s_ZsSjPU3h5U',
    appId: '1:106435358280:android:21cc46526b09e56754b27d',
    messagingSenderId: '106435358280',
    projectId: 'pairplay-e91f9',
    storageBucket: 'pairplay-e91f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7sajkpANvSH-kMJascxLg8Dmg8VPr8GI',
    appId: '1:106435358280:ios:6dcff5722983da2254b27d',
    messagingSenderId: '106435358280',
    projectId: 'pairplay-e91f9',
    storageBucket: 'pairplay-e91f9.firebasestorage.app',
    iosBundleId: 'com.example.pairplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7sajkpANvSH-kMJascxLg8Dmg8VPr8GI',
    appId: '1:106435358280:ios:6dcff5722983da2254b27d',
    messagingSenderId: '106435358280',
    projectId: 'pairplay-e91f9',
    storageBucket: 'pairplay-e91f9.firebasestorage.app',
    iosBundleId: 'com.example.pairplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOORPm7AP1SKj6S1GLsvdlKjCrUeJeQkE',
    appId: '1:106435358280:web:2592f92e641ca26d54b27d',
    messagingSenderId: '106435358280',
    projectId: 'pairplay-e91f9',
    authDomain: 'pairplay-e91f9.firebaseapp.com',
    storageBucket: 'pairplay-e91f9.firebasestorage.app',
    measurementId: 'G-L78W6QV54C',
  );
}
